public class PyramindRichness_V2{
 
 private without sharing class PyramidRichnessWrapper{
            public Id serviceId;
            public Id solutionId;
            public Id oppDelocID;
            
            public decimal sumOfRunYr1=0;
            public decimal sumOfRunYr2=0;
            public decimal sumOfRunYr3=0;
            public decimal sumOfRunYr4=0;
            public decimal sumOfRunYr5=0;
            public decimal sumOfRunYr6=0;
            public decimal sumOfRunYr7=0;
            public decimal sumOfRunYr8=0;
            public decimal sumOfRunYr9=0;
            public decimal sumOfRunYr10=0;

            public decimal sumOfFteYr1=0;
            public decimal sumOfFteYr2=0;
            public decimal sumOfFteYr3=0;
            public decimal sumOfFteYr4=0;
            public decimal sumOfFteYr5=0;
            public decimal sumOfFteYr6=0;
            public decimal sumOfFteYr7=0;
            public decimal sumOfFteYr8=0;
            public decimal sumOfFteYr9=0;
            public decimal sumOfFteYr10=0;

            public decimal sumOfFteYr1Lvl1=0;
            public decimal sumOfFteYr1Lvl2=0;
            public decimal sumOfFteYr1Lvl3=0;
            public decimal sumOfFteYr1Lvl4=0;
            public decimal sumOfFteYr1Lvl5=0;
            public decimal sumOfFteYr1Lvl6=0;
            public decimal sumOfFteYr1Lvl7=0;
            public decimal sumOfFteYr1Lvl8=0;
            public decimal sumOfSumFTEYr1=0;
            public decimal effSumOfSumFTEYr1=0;
            public decimal sumOfFteYr2Lvl1=0;
            public decimal sumOfFteYr2Lvl2=0;
            public decimal sumOfFteYr2Lvl3=0;
            public decimal sumOfFteYr2Lvl4=0;
            public decimal sumOfFteYr2Lvl5=0;
            public decimal sumOfFteYr2Lvl6=0;
            public decimal sumOfFteYr2Lvl7=0;
            public decimal sumOfFteYr2Lvl8=0;
            public decimal sumOfSumFTEYr2=0;
            public decimal effSumOfSumFTEYr2=0;
            public decimal sumOfFteYr3Lvl1=0;
            public decimal sumOfFteYr3Lvl2=0;
            public decimal sumOfFteYr3Lvl3=0;
            public decimal sumOfFteYr3Lvl4=0;
            public decimal sumOfFteYr3Lvl5=0;
            public decimal sumOfFteYr3Lvl6=0;
            public decimal sumOfFteYr3Lvl7=0;
            public decimal sumOfFteYr3Lvl8=0;
            public decimal sumOfSumFTEYr3=0;
            public decimal effSumOfSumFTEYr3=0;
            public decimal sumOfFteYr4Lvl1=0;
            public decimal sumOfFteYr4Lvl2=0;
            public decimal sumOfFteYr4Lvl3=0;
            public decimal sumOfFteYr4Lvl4=0;
            public decimal sumOfFteYr4Lvl5=0;
            public decimal sumOfFteYr4Lvl6=0;
            public decimal sumOfFteYr4Lvl7=0;
            public decimal sumOfFteYr4Lvl8=0;
            public decimal sumOfSumFTEYr4=0;
            public decimal effSumOfSumFTEYr4=0;
            public decimal sumOfFteYr5Lvl1=0;
            public decimal sumOfFteYr5Lvl2=0;
            public decimal sumOfFteYr5Lvl3=0;
            public decimal sumOfFteYr5Lvl4=0;
            public decimal sumOfFteYr5Lvl5=0;
            public decimal sumOfFteYr5Lvl6=0;
            public decimal sumOfFteYr5Lvl7=0;
            public decimal sumOfFteYr5Lvl8=0;
            public decimal sumOfSumFTEYr5=0;
            public decimal effSumOfSumFTEYr5=0;
            public decimal sumOfFteYr6Lvl1=0;
            public decimal sumOfFteYr6Lvl2=0;
            public decimal sumOfFteYr6Lvl3=0;
            public decimal sumOfFteYr6Lvl4=0;
            public decimal sumOfFteYr6Lvl5=0;
            public decimal sumOfFteYr6Lvl6=0;
            public decimal sumOfFteYr6Lvl7=0;
            public decimal sumOfFteYr6Lvl8=0;
            public decimal sumOfSumFTEYr6=0;
            public decimal effSumOfSumFTEYr6=0;
            public decimal sumOfFteYr7Lvl1=0;
            public decimal sumOfFteYr7Lvl2=0;
            public decimal sumOfFteYr7Lvl3=0;
            public decimal sumOfFteYr7Lvl4=0;
            public decimal sumOfFteYr7Lvl5=0;
            public decimal sumOfFteYr7Lvl6=0;
            public decimal sumOfFteYr7Lvl7=0;
            public decimal sumOfFteYr7Lvl8=0;
            public decimal sumOfSumFTEYr7=0;
            public decimal effSumOfSumFTEYr7=0;
            public decimal sumOfFteYr8Lvl1=0;
            public decimal sumOfFteYr8Lvl2=0;
            public decimal sumOfFteYr8Lvl3=0;
            public decimal sumOfFteYr8Lvl4=0;
            public decimal sumOfFteYr8Lvl5=0;
            public decimal sumOfFteYr8Lvl6=0;
            public decimal sumOfFteYr8Lvl7=0;
            public decimal sumOfFteYr8Lvl8=0;
            public decimal sumOfSumFTEYr8=0;
            public decimal effSumOfSumFTEYr8=0;
            public decimal sumOfFteYr9Lvl1=0;
            public decimal sumOfFteYr9Lvl2=0;
            public decimal sumOfFteYr9Lvl3=0;
            public decimal sumOfFteYr9Lvl4=0;
            public decimal sumOfFteYr9Lvl5=0;
            public decimal sumOfFteYr9Lvl6=0;
            public decimal sumOfFteYr9Lvl7=0;
            public decimal sumOfFteYr9Lvl8=0;
            public decimal sumOfSumFTEYr9=0;
            public decimal effSumOfSumFTEYr9=0;
            public decimal sumOfFteYr10Lvl1=0;
            public decimal sumOfFteYr10Lvl2=0;
            public decimal sumOfFteYr10Lvl3=0;
            public decimal sumOfFteYr10Lvl4=0;
            public decimal sumOfFteYr10Lvl5=0;
            public decimal sumOfFteYr10Lvl6=0;
            public decimal sumOfFteYr10Lvl7=0;
            public decimal sumOfFteYr10Lvl8=0;
            public decimal sumOfSumFTEYr10=0;
            public decimal effSumOfSumFTEYr10=0;
}


public static void pyramidRichness(Set<Id> nFTEIds, List<Service__c> serviceList, List<Solution_Scope__c> solutionList, Opportunity opp, List<Opportunity_Delivery_Location__c> delLocList){


    try{

    delLocPyrRichnessCalc(nFTEIds, delLocList);
    List<FTE_Details__c> inputFTEDetail = [SELECT Career_Level__r.Name, Opportunity_Delivery_Location__c, Service__r.Services__r.name,Sub_Service_Group__r.Offering_Master__r.name,
                                        Career_Level__c,Costing_Type__c,Opportunity__c,Sub_Service_Group__c,Sub_Service_Group__r.Name,
                                        Service_Component_Name__c,Service_Component__c,Service_Group__c,
                                        Service_Name__c,Service__c,Service__r.Serv_Nm__c,Sub_Service_Group_Name__c,
                                        Mob_Totals__c,FTEYr1__c,FTEYr2__c,FTEYr3__c,FTEYr4__c,FTEYr5__c,FTEYr6__c,FTEYr7__c,
                                        FTEYr8__c,FTEYr9__c,FTEYr10__c,FTEMobTotals__c,Delivery_Location__r.Name,
                                        Run_Yr1__c,Run_Yr2__c,Run_Yr3__c,Run_Yr4__c,Run_Yr5__c,Run_Yr6__c,Run_Yr7__c,Run_Yr8__c,Run_Yr9__c,Run_Yr10__c,
                                        Opportunity_Delivery_Location__r.Delivery_Location__r.name,Costing_Request__r.Opportunity__c,Service__r.Delivery_Locations__c 
                                        FROM FTE_Details__c WHERE ID IN :nFTEids  LIMIT 10000];
                                
    Map<Id, PyramidRichnessWrapper> svcPyrMap = new Map<Id, PyramidRichnessWrapper>();
    Map<Id, PyramidRichnessWrapper> solnPyrMap =  new Map<Id, PyramidRichnessWrapper>();
    Map<Id, PyramidRichnessWrapper> oppDLocMap =  new Map<Id, PyramidRichnessWrapper>();
    PyramidRichnessWrapper svcPyrWrap ;
    PyramidRichnessWrapper oppDelWrap;


    
     for(FTE_Details__c fterec: inputFTEDetail){
        
        svcPyrWrap= new PyramidRichnessWrapper ();
        
        if(!svcPyrMap.containsKey(fterec.service__c)){
            
            svcPyrWrap.serviceId = fterec.service__c;
            svcPyrWrap.solutionId = fteRec.Sub_Service_Group__c;
            svcPyrWrap.oppDelocID = fteRec.Opportunity_Delivery_Location__c;
        }
        else{
            svcPyrWrap = svcPyrMap.get(fterec.service__c);
        }
        
            svcPyrWrap.sumOfRunYr1+= fterec.Run_Yr1__c;
            svcPyrWrap.sumOfRunYr2+= fterec.Run_Yr2__c;
            svcPyrWrap.sumOfRunYr3+= fterec.Run_Yr3__c;
            svcPyrWrap.sumOfRunYr4+= fterec.Run_Yr4__c;
            svcPyrWrap.sumOfRunYr5+= fterec.Run_Yr5__c;
            svcPyrWrap.sumOfRunYr6+= fterec.Run_Yr6__c;
            svcPyrWrap.sumOfRunYr7+= fterec.Run_Yr7__c;
            svcPyrWrap.sumOfRunYr8+= fterec.Run_Yr8__c;
            svcPyrWrap.sumOfRunYr9+= fterec.Run_Yr9__c;
            svcPyrWrap.sumOfRunYr10+= fterec.Run_Yr10__c;
            svcPyrWrap.sumOfFteYr1+= fterec.FteYr1__c;
            svcPyrWrap.sumOfFteYr2+= fterec.FteYr2__c;
            svcPyrWrap.sumOfFteYr3+= fterec.FteYr3__c;
            svcPyrWrap.sumOfFteYr4+= fterec.FteYr4__c;
            svcPyrWrap.sumOfFteYr5+= fterec.FteYr5__c;
            svcPyrWrap.sumOfFteYr6+= fterec.FteYr6__c;
            svcPyrWrap.sumOfFteYr7+= fterec.FteYr7__c;
            svcPyrWrap.sumOfFteYr8+= fterec.FteYr8__c;
            svcPyrWrap.sumOfFteYr9+= fterec.FteYr9__c;
            svcPyrWrap.sumOfFteYr10+= fterec.FteYr10__c;
        
        if(UtilConstants.SDO.equalsIgnoreCase(fterec.Costing_Type__c)  ){
            //System.debug('>>>>>>> ' + svcPyrWrap);
            //calculation for pyramid richness
                    if(UtilConstants.ASSOCIATE13.equalsIgnoreCase(fterec.Career_Level__r.Name)){
                        svcPyrWrap.sumOfFteYr1Lvl1+= fterec.FTEYr1__c;
                        svcPyrWrap.sumOfFteYr2Lvl1+= fterec.FTEYr2__c;
                        svcPyrWrap.sumOfFteYr3Lvl1+= fterec.FTEYr3__c;
                        svcPyrWrap.sumOfFteYr4Lvl1+= fterec.FTEYr4__c;
                        svcPyrWrap.sumOfFteYr5Lvl1+= fterec.FTEYr5__c;
                        svcPyrWrap.sumOfFteYr6Lvl1+= fterec.FTEYr6__c;
                        svcPyrWrap.sumOfFteYr7Lvl1+= fterec.FTEYr7__c;
                        svcPyrWrap.sumOfFteYr8Lvl1+= fterec.FTEYr8__c;
                        svcPyrWrap.sumOfFteYr9Lvl1+= fterec.FTEYr9__c;
                        svcPyrWrap.sumOfFteYr10Lvl1+=fterec.FTEYr10__c;
                    }else if(UtilConstants.ASSOCIATE12.equalsIgnoreCase(fterec.Career_Level__r.Name)){
                        svcPyrWrap.sumOfFteYr1Lvl2+= fterec.FTEYr1__c;
                        svcPyrWrap.sumOfFteYr2Lvl2+= fterec.FTEYr2__c;
                        svcPyrWrap.sumOfFteYr3Lvl2+= fterec.FTEYr3__c;
                        svcPyrWrap.sumOfFteYr4Lvl2+= fterec.FTEYr4__c;
                        svcPyrWrap.sumOfFteYr5Lvl2+= fterec.FTEYr5__c;
                        svcPyrWrap.sumOfFteYr6Lvl2+= fterec.FTEYr6__c;
                        svcPyrWrap.sumOfFteYr7Lvl2+= fterec.FTEYr7__c;
                        svcPyrWrap.sumOfFteYr8Lvl2+= fterec.FTEYr8__c;
                        svcPyrWrap.sumOfFteYr9Lvl2+= fterec.FTEYr9__c;
                        svcPyrWrap.sumOfFteYr10Lvl2+=fterec.FTEYr10__c;
                    }else if(UtilConstants.ANALYST11.equalsIgnoreCase(fterec.Career_Level__r.Name)){
                        svcPyrWrap.sumOfFteYr1Lvl3+= fterec.FTEYr1__c;
                        svcPyrWrap.sumOfFteYr2Lvl3+= fterec.FTEYr2__c;
                        svcPyrWrap.sumOfFteYr3Lvl3+= fterec.FTEYr3__c;
                        svcPyrWrap.sumOfFteYr4Lvl3+= fterec.FTEYr4__c;
                        svcPyrWrap.sumOfFteYr5Lvl3+= fterec.FTEYr5__c;
                        svcPyrWrap.sumOfFteYr6Lvl3+= fterec.FTEYr6__c;
                        svcPyrWrap.sumOfFteYr7Lvl3+= fterec.FTEYr7__c;
                        svcPyrWrap.sumOfFteYr8Lvl3+= fterec.FTEYr8__c;
                        svcPyrWrap.sumOfFteYr9Lvl3+= fterec.FTEYr9__c;
                        svcPyrWrap.sumOfFteYr10Lvl3+=fterec.FTEYr10__c;
                    }else if(UtilConstants.ANALYST10.equalsIgnoreCase(fterec.Career_Level__r.Name)){
                        svcPyrWrap.sumOfFteYr1Lvl4+= fterec.FTEYr1__c;
                        svcPyrWrap.sumOfFteYr2Lvl4+= fterec.FTEYr2__c;
                        svcPyrWrap.sumOfFteYr3Lvl4+= fterec.FTEYr3__c;
                        svcPyrWrap.sumOfFteYr4Lvl4+= fterec.FTEYr4__c;
                        svcPyrWrap.sumOfFteYr5Lvl4+= fterec.FTEYr5__c;
                        svcPyrWrap.sumOfFteYr6Lvl4+= fterec.FTEYr6__c;
                        svcPyrWrap.sumOfFteYr7Lvl4+= fterec.FTEYr7__c;
                        svcPyrWrap.sumOfFteYr8Lvl4+= fterec.FTEYr8__c;
                        svcPyrWrap.sumOfFteYr9Lvl4+= fterec.FTEYr9__c;
                        svcPyrWrap.sumOfFteYr10Lvl4+=fterec.FTEYr10__c;
                    }else if(UtilConstants.CONSULTANT9.equalsIgnoreCase(fterec.Career_Level__r.Name)){
                        svcPyrWrap.sumOfFteYr1Lvl5+= fterec.FTEYr1__c;
                        svcPyrWrap.sumOfFteYr2Lvl5+= fterec.FTEYr2__c;
                        svcPyrWrap.sumOfFteYr3Lvl5+= fterec.FTEYr3__c;
                        svcPyrWrap.sumOfFteYr4Lvl5+= fterec.FTEYr4__c;
                        svcPyrWrap.sumOfFteYr5Lvl5+= fterec.FTEYr5__c;
                        svcPyrWrap.sumOfFteYr6Lvl5+= fterec.FTEYr6__c;
                        svcPyrWrap.sumOfFteYr7Lvl5+= fterec.FTEYr7__c;
                        svcPyrWrap.sumOfFteYr8Lvl5+= fterec.FTEYr8__c;
                        svcPyrWrap.sumOfFteYr9Lvl5+= fterec.FTEYr9__c;
                        svcPyrWrap.sumOfFteYr10Lvl5+=fterec.FTEYr10__c;
                    }else if(UtilConstants.CONSULTANT8.equalsIgnoreCase(fterec.Career_Level__r.Name)){
                        svcPyrWrap.sumOfFteYr1Lvl6+= fterec.FTEYr1__c;
                        svcPyrWrap.sumOfFteYr2Lvl6+= fterec.FTEYr2__c;
                        svcPyrWrap.sumOfFteYr3Lvl6+= fterec.FTEYr3__c;
                        svcPyrWrap.sumOfFteYr4Lvl6+= fterec.FTEYr4__c;
                        svcPyrWrap.sumOfFteYr5Lvl6+= fterec.FTEYr5__c;
                        svcPyrWrap.sumOfFteYr6Lvl6+= fterec.FTEYr6__c;
                        svcPyrWrap.sumOfFteYr7Lvl6+= fterec.FTEYr7__c;
                        svcPyrWrap.sumOfFteYr8Lvl6+= fterec.FTEYr8__c;
                        svcPyrWrap.sumOfFteYr9Lvl6+= fterec.FTEYr9__c;
                        svcPyrWrap.sumOfFteYr10Lvl6+=fterec.FTEYr10__c;
                    }else if(UtilConstants.MANAGER7.equalsIgnoreCase(fterec.Career_Level__r.Name)){
                        svcPyrWrap.sumOfFteYr1Lvl7+= fterec.FTEYr1__c;
                        svcPyrWrap.sumOfFteYr2Lvl7+= fterec.FTEYr2__c;
                        svcPyrWrap.sumOfFteYr3Lvl7+= fterec.FTEYr3__c;
                        svcPyrWrap.sumOfFteYr4Lvl7+= fterec.FTEYr4__c;
                        svcPyrWrap.sumOfFteYr5Lvl7+= fterec.FTEYr5__c;
                        svcPyrWrap.sumOfFteYr6Lvl7+= fterec.FTEYr6__c;
                        svcPyrWrap.sumOfFteYr7Lvl7+= fterec.FTEYr7__c;
                        svcPyrWrap.sumOfFteYr8Lvl7+= fterec.FTEYr8__c;
                        svcPyrWrap.sumOfFteYr9Lvl7+= fterec.FTEYr9__c;
                        svcPyrWrap.sumOfFteYr10Lvl7+=fterec.FTEYr10__c;
                    }else if(UtilConstants.SENIORMANAGER6.equalsIgnoreCase(fterec.Career_Level__r.Name) || UtilConstants.SENIORMANAGER5.equalsIgnoreCase(fterec.Career_Level__r.Name)){
                        svcPyrWrap.sumOfFteYr1Lvl8+= fterec.FTEYr1__c;
                        svcPyrWrap.sumOfFteYr2Lvl8+= fterec.FTEYr2__c;
                        svcPyrWrap.sumOfFteYr3Lvl8+= fterec.FTEYr3__c;
                        svcPyrWrap.sumOfFteYr4Lvl8+= fterec.FTEYr4__c;
                        svcPyrWrap.sumOfFteYr5Lvl8+= fterec.FTEYr5__c;
                        svcPyrWrap.sumOfFteYr6Lvl8+= fterec.FTEYr6__c;
                        svcPyrWrap.sumOfFteYr7Lvl8+= fterec.FTEYr7__c;
                        svcPyrWrap.sumOfFteYr8Lvl8+= fterec.FTEYr8__c;
                        svcPyrWrap.sumOfFteYr9Lvl8+= fterec.FTEYr9__c;
                        svcPyrWrap.sumOfFteYr10Lvl8+=fterec.FTEYr10__c;
                    }else{}
                    
           
            //System.debug('fteRec>>>> ' + fteRec);
            //System.debug('svcPyrWrap>>>> ' + svcPyrWrap);
            //svcPyrWrap = null;
        }
        svcPyrMap.put(fteRec.service__c, svcPyrWrap); 
    }
    
    //System.debug('svcPyrMap size' + svcPyrMap.size());
    //System.debug('svcPyrMap size????' + svcPyrMap);
    
    //Commented code
    
    for(Service__c svc : serviceList){
        
        PyramidRichnessWrapper solPyrWrap;
        
        if(svcPyrMap.containsKey(svc.Id)){
            PyramidRichnessWrapper svcWrap= new PyramidRichnessWrapper();
            svcWrap= svcPyrMap.get(svc.Id);
            
            
            svcWrap.sumOfSumFTEYr1 = svcWrap.sumOfFteYr1Lvl1 + svcWrap.sumOfFteYr1Lvl2 + svcWrap.sumOfFteYr1Lvl3 + svcWrap.sumOfFteYr1Lvl4 + svcWrap.sumOfFteYr1Lvl5 + svcWrap.sumOfFteYr1Lvl6 + svcWrap.sumOfFteYr1Lvl7 + svcWrap.sumOfFteYr1Lvl8;
            svcWrap.effSumOfSumFTEYr1 = svcWrap.sumOfFteYr1Lvl1*1 + svcWrap.sumOfFteYr1Lvl2*2 + svcWrap.sumOfFteYr1Lvl3*3 + svcWrap.sumOfFteYr1Lvl4*4 + svcWrap.sumOfFteYr1Lvl5*5 + svcWrap.sumOfFteYr1Lvl6*6 + svcWrap.sumOfFteYr1Lvl7*7 + svcWrap.sumOfFteYr1Lvl8*8;
           
            svcWrap.sumOfSumFTEYr2 = svcWrap.sumOfFteYr2Lvl1 + svcWrap.sumOfFteYr2Lvl2 + svcWrap.sumOfFteYr2Lvl3 + svcWrap.sumOfFteYr2Lvl4 + svcWrap.sumOfFteYr2Lvl5 + svcWrap.sumOfFteYr2Lvl6 + svcWrap.sumOfFteYr2Lvl7 + svcWrap.sumOfFteYr2Lvl8;
            svcWrap.effSumOfSumFTEYr2 = svcWrap.sumOfFteYr2Lvl1*1 + svcWrap.sumOfFteYr2Lvl2*2 + svcWrap.sumOfFteYr2Lvl3*3 + svcWrap.sumOfFteYr2Lvl4*4 + svcWrap.sumOfFteYr2Lvl5*5 + svcWrap.sumOfFteYr2Lvl6*6 + svcWrap.sumOfFteYr2Lvl7*7 + svcWrap.sumOfFteYr2Lvl8*8;
           
            
            svcWrap.sumOfSumFTEYr3 = svcWrap.sumOfFteYr3Lvl1 + svcWrap.sumOfFteYr3Lvl2 + svcWrap.sumOfFteYr3Lvl3 + svcWrap.sumOfFteYr3Lvl4 + svcWrap.sumOfFteYr3Lvl5 + svcWrap.sumOfFteYr3Lvl6 + svcWrap.sumOfFteYr3Lvl7 + svcWrap.sumOfFteYr3Lvl8;
            svcWrap.effSumOfSumFTEYr3 = svcWrap.sumOfFteYr3Lvl1*1 + svcWrap.sumOfFteYr3Lvl2*2 + svcWrap.sumOfFteYr3Lvl3*3 + svcWrap.sumOfFteYr3Lvl4*4 + svcWrap.sumOfFteYr3Lvl5*5 + svcWrap.sumOfFteYr3Lvl6*6 + svcWrap.sumOfFteYr3Lvl7*7 + svcWrap.sumOfFteYr3Lvl8*8;
            
            svcWrap.sumOfSumFTEYr4 = svcWrap.sumOfFteYr4Lvl1 + svcWrap.sumOfFteYr4Lvl2 + svcWrap.sumOfFteYr4Lvl3 + svcWrap.sumOfFteYr4Lvl4 + svcWrap.sumOfFteYr4Lvl5 + svcWrap.sumOfFteYr4Lvl6 + svcWrap.sumOfFteYr4Lvl7 + svcWrap.sumOfFteYr4Lvl8;
            svcWrap.effSumOfSumFTEYr4 = svcWrap.sumOfFteYr4Lvl1*1 + svcWrap.sumOfFteYr4Lvl2*2 + svcWrap.sumOfFteYr4Lvl3*3 + svcWrap.sumOfFteYr4Lvl4*4 + svcWrap.sumOfFteYr4Lvl5*5 + svcWrap.sumOfFteYr4Lvl6*6 + svcWrap.sumOfFteYr4Lvl7*7 + svcWrap.sumOfFteYr4Lvl8*8;
            
            svcWrap.sumOfSumFTEYr5 = svcWrap.sumOfFteYr5Lvl1 + svcWrap.sumOfFteYr5Lvl2 + svcWrap.sumOfFteYr5Lvl3 + svcWrap.sumOfFteYr5Lvl4 + svcWrap.sumOfFteYr5Lvl5 + svcWrap.sumOfFteYr5Lvl6 + svcWrap.sumOfFteYr5Lvl7 + svcWrap.sumOfFteYr5Lvl8;
            svcWrap.effSumOfSumFTEYr5 = svcWrap.sumOfFteYr5Lvl1*1 + svcWrap.sumOfFteYr5Lvl2*2 + svcWrap.sumOfFteYr5Lvl3*3 + svcWrap.sumOfFteYr5Lvl4*4 + svcWrap.sumOfFteYr5Lvl5*5 + svcWrap.sumOfFteYr5Lvl6*6 + svcWrap.sumOfFteYr5Lvl7*7 + svcWrap.sumOfFteYr5Lvl8*8;
            
            svcWrap.sumOfSumFTEYr6 = svcWrap.sumOfFteYr6Lvl1 + svcWrap.sumOfFteYr6Lvl2 + svcWrap.sumOfFteYr6Lvl3 + svcWrap.sumOfFteYr6Lvl4 + svcWrap.sumOfFteYr6Lvl5 + svcWrap.sumOfFteYr6Lvl6 + svcWrap.sumOfFteYr6Lvl7 + svcWrap.sumOfFteYr6Lvl8;
            svcWrap.effSumOfSumFTEYr6 = svcWrap.sumOfFteYr6Lvl1*1 + svcWrap.sumOfFteYr6Lvl2*2 + svcWrap.sumOfFteYr6Lvl3*3 + svcWrap.sumOfFteYr6Lvl4*4 + svcWrap.sumOfFteYr6Lvl5*5 + svcWrap.sumOfFteYr6Lvl6*6 + svcWrap.sumOfFteYr6Lvl7*7 + svcWrap.sumOfFteYr6Lvl8*8;
            
            svcWrap.sumOfSumFTEYr7 = svcWrap.sumOfFteYr7Lvl1 + svcWrap.sumOfFteYr7Lvl2 + svcWrap.sumOfFteYr7Lvl3 + svcWrap.sumOfFteYr7Lvl4 + svcWrap.sumOfFteYr7Lvl5 + svcWrap.sumOfFteYr7Lvl6 + svcWrap.sumOfFteYr7Lvl7 + svcWrap.sumOfFteYr7Lvl8;
            svcWrap.effSumOfSumFTEYr7 = svcWrap.sumOfFteYr7Lvl1*1 + svcWrap.sumOfFteYr7Lvl2*2 + svcWrap.sumOfFteYr7Lvl3*3 + svcWrap.sumOfFteYr7Lvl4*4 + svcWrap.sumOfFteYr7Lvl5*5 + svcWrap.sumOfFteYr7Lvl6*6 + svcWrap.sumOfFteYr7Lvl7*7 + svcWrap.sumOfFteYr7Lvl8*8;
            
            svcWrap.sumOfSumFTEYr8 = svcWrap.sumOfFteYr8Lvl1 + svcWrap.sumOfFteYr8Lvl2 + svcWrap.sumOfFteYr8Lvl3 + svcWrap.sumOfFteYr8Lvl4 + svcWrap.sumOfFteYr8Lvl5 + svcWrap.sumOfFteYr8Lvl6 + svcWrap.sumOfFteYr8Lvl7 + svcWrap.sumOfFteYr8Lvl8;
            svcWrap.effSumOfSumFTEYr8 = svcWrap.sumOfFteYr8Lvl1*1 + svcWrap.sumOfFteYr8Lvl2*2 + svcWrap.sumOfFteYr8Lvl3*3 + svcWrap.sumOfFteYr8Lvl4*4 + svcWrap.sumOfFteYr8Lvl5*5 + svcWrap.sumOfFteYr8Lvl6*6 + svcWrap.sumOfFteYr8Lvl7*7 + svcWrap.sumOfFteYr8Lvl8*8;
            
            svcWrap.sumOfSumFTEYr9 = svcWrap.sumOfFteYr9Lvl1 + svcWrap.sumOfFteYr9Lvl2 + svcWrap.sumOfFteYr9Lvl3 + svcWrap.sumOfFteYr9Lvl4 + svcWrap.sumOfFteYr9Lvl5 + svcWrap.sumOfFteYr9Lvl6 + svcWrap.sumOfFteYr9Lvl7 + svcWrap.sumOfFteYr9Lvl8;
            svcWrap.effSumOfSumFTEYr9 = svcWrap.sumOfFteYr9Lvl1*1 + svcWrap.sumOfFteYr9Lvl2*2 + svcWrap.sumOfFteYr9Lvl3*3 + svcWrap.sumOfFteYr9Lvl4*4 + svcWrap.sumOfFteYr9Lvl5*5 + svcWrap.sumOfFteYr9Lvl6*6 + svcWrap.sumOfFteYr9Lvl7*7 + svcWrap.sumOfFteYr9Lvl8*8;
            
            svcWrap.sumOfSumFTEYr10 = svcWrap.sumOfFteYr10Lvl1 + svcWrap.sumOfFteYr10Lvl2 + svcWrap.sumOfFteYr10Lvl3 + svcWrap.sumOfFteYr10Lvl4 + svcWrap.sumOfFteYr10Lvl5 + svcWrap.sumOfFteYr10Lvl6 + svcWrap.sumOfFteYr10Lvl7 + svcWrap.sumOfFteYr10Lvl8;
            svcWrap.effSumOfSumFTEYr10 = svcWrap.sumOfFteYr10Lvl1*1 + svcWrap.sumOfFteYr10Lvl2*2 + svcWrap.sumOfFteYr10Lvl3*3 + svcWrap.sumOfFteYr10Lvl4*4 + svcWrap.sumOfFteYr10Lvl5*5 + svcWrap.sumOfFteYr10Lvl6*6 + svcWrap.sumOfFteYr10Lvl7*7 + svcWrap.sumOfFteYr10Lvl8*8;
            
                
            svc.PyramidRichnessY1__c  = (svcWrap.effSumOfSumFTEYr1==0)?0: (svcWrap.sumOfSumFTEYr1/ svcWrap.effSumOfSumFTEYr1).setScale(4);
            svc.PyramidRichnessY2__c  = (svcWrap.effSumOfSumFTEYr2==0)?0: (svcWrap.sumOfSumFTEYr2/ svcWrap.effSumOfSumFTEYr2).setScale(4);
            svc.PyramidRichnessY3__c  = (svcWrap.effSumOfSumFTEYr3==0)?0: (svcWrap.sumOfSumFTEYr3/ svcWrap.effSumOfSumFTEYr3).setScale(4);
            svc.PyramidRichnessY4__c  = (svcWrap.effSumOfSumFTEYr4==0)?0: (svcWrap.sumOfSumFTEYr4/ svcWrap.effSumOfSumFTEYr4).setScale(4);
            svc.PyramidRichnessY5__c  = (svcWrap.effSumOfSumFTEYr5==0)?0: (svcWrap.sumOfSumFTEYr5/ svcWrap.effSumOfSumFTEYr5).setScale(4);
            svc.PyramidRichnessY6__c  = (svcWrap.effSumOfSumFTEYr6==0)?0: (svcWrap.sumOfSumFTEYr6/ svcWrap.effSumOfSumFTEYr6).setScale(4);
            svc.PyramidRichnessY7__c  = (svcWrap.effSumOfSumFTEYr7==0)?0: (svcWrap.sumOfSumFTEYr7/ svcWrap.effSumOfSumFTEYr7).setScale(4);
            svc.PyramidRichnessY8__c  = (svcWrap.effSumOfSumFTEYr8==0)?0: (svcWrap.sumOfSumFTEYr8/ svcWrap.effSumOfSumFTEYr8).setScale(4);
            svc.PyramidRichnessY9__c  = (svcWrap.effSumOfSumFTEYr9==0)?0: (svcWrap.sumOfSumFTEYr9/ svcWrap.effSumOfSumFTEYr9).setScale(4);
            svc.PyramidRichnessY10__c  = (svcWrap.effSumOfSumFTEYr10==0)?0: (svcWrap.sumOfSumFTEYr10/ svcWrap.effSumOfSumFTEYr10).setScale(4);
            
            svc.Cost_Per_FTE_Y1__c = (svcWrap.sumOfFteYr1==0)?0: (svcWrap.sumOfRunYr1/ svcWrap.sumOfFteYr1).setScale(4);
            svc.Cost_Per_FTE_Y2__c = (svcWrap.sumOfFteYr2==0)?0: (svcWrap.sumOfRunYr2/ svcWrap.sumOfFteYr2).setScale(4);
            svc.Cost_Per_FTE_Y3__c = (svcWrap.sumOfFteYr3==0)?0: (svcWrap.sumOfRunYr3/ svcWrap.sumOfFteYr3).setScale(4);
            svc.Cost_Per_FTE_Y4__c = (svcWrap.sumOfFteYr4==0)?0: (svcWrap.sumOfRunYr4/ svcWrap.sumOfFteYr4).setScale(4);
            svc.Cost_Per_FTE_Y5__c = (svcWrap.sumOfFteYr5==0)?0: (svcWrap.sumOfRunYr5/ svcWrap.sumOfFteYr5).setScale(4);
            svc.Cost_Per_FTE_Y6__c = (svcWrap.sumOfFteYr6==0)?0: (svcWrap.sumOfRunYr6/ svcWrap.sumOfFteYr6).setScale(4);
            svc.Cost_Per_FTE_Y7__c = (svcWrap.sumOfFteYr7==0)?0: (svcWrap.sumOfRunYr7/ svcWrap.sumOfFteYr7).setScale(4);
            svc.Cost_Per_FTE_Y8__c = (svcWrap.sumOfFteYr8==0)?0: (svcWrap.sumOfRunYr8/ svcWrap.sumOfFteYr8).setScale(4);
            svc.Cost_Per_FTE_Y9__c = (svcWrap.sumOfFteYr9==0)?0: (svcWrap.sumOfRunYr9/ svcWrap.sumOfFteYr9).setScale(4);
            svc.Cost_Per_FTE_Y10__c = (svcWrap.sumOfFteYr10==0)?0: (svcWrap.sumOfRunYr10/ svcWrap.sumOfFteYr10).setScale(4);             
                
            solPyrWrap= new PyramidRichnessWrapper();
           
            
            if(!solnPyrMap.containsKey(svc.Solutionscope__c)){
                //solPyrWrap= new PyramidRichnessWrapper();
                solPyrWrap.solutionId = svc.Solutionscope__c;
            }
            else{
                solPyrWrap= solnPyrMap.get(svc.Solutionscope__c);
            } 
                
              solPyrWrap.sumOfSumFTEYr1+= svcWrap.sumOfSumFTEYr1;
              solPyrWrap.sumOfSumFTEYr2+= svcWrap.sumOfSumFTEYr2;
              solPyrWrap.sumOfSumFTEYr3+= svcWrap.sumOfSumFTEYr3;
              solPyrWrap.sumOfSumFTEYr4+= svcWrap.sumOfSumFTEYr4;
              solPyrWrap.sumOfSumFTEYr5+= svcWrap.sumOfSumFTEYr5;
              solPyrWrap.sumOfSumFTEYr6+= svcWrap.sumOfSumFTEYr6;
              solPyrWrap.sumOfSumFTEYr7+= svcWrap.sumOfSumFTEYr7;
              solPyrWrap.sumOfSumFTEYr8+= svcWrap.sumOfSumFTEYr8;
              solPyrWrap.sumOfSumFTEYr9+= svcWrap.sumOfSumFTEYr9;
              solPyrWrap.sumOfSumFTEYr10+= svcWrap.sumOfSumFTEYr10;
              solPyrWrap.effSumOfSumFTEYr1+= svcWrap.effsumOfSumFTEYr1;
              solPyrWrap.effsumOfSumFTEYr2+= svcWrap.effsumOfSumFTEYr2;
              solPyrWrap.effsumOfSumFTEYr3+= svcWrap.effsumOfSumFTEYr3;
              solPyrWrap.effsumOfSumFTEYr4+= svcWrap.effsumOfSumFTEYr4;
              solPyrWrap.effsumOfSumFTEYr5+= svcWrap.effsumOfSumFTEYr5;
              solPyrWrap.effsumOfSumFTEYr6+= svcWrap.effsumOfSumFTEYr6;
              solPyrWrap.effsumOfSumFTEYr7+= svcWrap.effsumOfSumFTEYr7;
              solPyrWrap.effsumOfSumFTEYr8+= svcWrap.effsumOfSumFTEYr8;
              solPyrWrap.effsumOfSumFTEYr9+= svcWrap.effsumOfSumFTEYr9;
              solPyrWrap.effsumOfSumFTEYr10+= svcWrap.effsumOfSumFTEYr10;
              
              
                solPyrWrap.sumOfRunYr1+= svcWrap.sumOfRunYr1;
                solPyrWrap.sumOfRunYr2+= svcWrap.sumOfRunYr2;
                solPyrWrap.sumOfRunYr3+= svcWrap.sumOfRunYr3;
                solPyrWrap.sumOfRunYr4+= svcWrap.sumOfRunYr4;
                solPyrWrap.sumOfRunYr5+= svcWrap.sumOfRunYr5;
                solPyrWrap.sumOfRunYr6+= svcWrap.sumOfRunYr6;
                solPyrWrap.sumOfRunYr7+= svcWrap.sumOfRunYr7;
                solPyrWrap.sumOfRunYr8+= svcWrap.sumOfRunYr8;
                solPyrWrap.sumOfRunYr9+= svcWrap.sumOfRunYr9;
                solPyrWrap.sumOfRunYr10+= svcWrap.sumOfRunYr10;
                solPyrWrap.sumOfFteYr1+= svcWrap.sumOfFteYr1;
                solPyrWrap.sumOfFteYr2+= svcWrap.sumOfFteYr2;
                solPyrWrap.sumOfFteYr3+= svcWrap.sumOfFteYr3;
                solPyrWrap.sumOfFteYr4+= svcWrap.sumOfFteYr4;
                solPyrWrap.sumOfFteYr5+= svcWrap.sumOfFteYr5;
                solPyrWrap.sumOfFteYr6+= svcWrap.sumOfFteYr6;
                solPyrWrap.sumOfFteYr7+= svcWrap.sumOfFteYr7;
                solPyrWrap.sumOfFteYr8+= svcWrap.sumOfFteYr8;
                solPyrWrap.sumOfFteYr9+= svcWrap.sumOfFteYr9;
                solPyrWrap.sumOfFteYr10+= svcWrap.sumOfFteYr10;
             
              solnPyrMap.put(svc.Solutionscope__c, solPyrWrap);

            System.debug('solPyrWrap >> ' + solPyrWrap);
            //solPyrWrap= new PyramidRichnessWrapper();
            //svcWrap= new PyramidRichnessWrapper();
        }   
    }
    
    System.debug('solnPyrMap size' + solnPyrMap.size());
     System.debug('solnPyrMap size?????' + solnPyrMap);
    
    PyramidRichnessWrapper solPyr   = new PyramidRichnessWrapper();
    PyramidRichnessWrapper oppWrap = new PyramidRichnessWrapper();
    for(Solution_Scope__c  sol : solutionList){
        
        if(solnPyrMap.containsKey(sol.Id)){
            solPyr = new PyramidRichnessWrapper();
            solPyr = solnPyrMap.get(sol.Id);
             
            sol.PyramidRichnessY1__c  = (solPyr.effSumOfSumFTEYr1==0)?0: (solPyr.sumOfSumFTEYr1/ solPyr.effSumOfSumFTEYr1).setScale(4);
            sol.PyramidRichnessY2__c  = (solPyr.effSumOfSumFTEYr2==0)?0: (solPyr.sumOfSumFTEYr2/ solPyr.effSumOfSumFTEYr2).setScale(4);
            sol.PyramidRichnessY3__c  = (solPyr.effSumOfSumFTEYr3==0)?0: (solPyr.sumOfSumFTEYr3/ solPyr.effSumOfSumFTEYr3).setScale(4);
            sol.PyramidRichnessY4__c  = (solPyr.effSumOfSumFTEYr4==0)?0: (solPyr.sumOfSumFTEYr4/ solPyr.effSumOfSumFTEYr4).setScale(4);
            sol.PyramidRichnessY5__c  = (solPyr.effSumOfSumFTEYr5==0)?0: (solPyr.sumOfSumFTEYr5/ solPyr.effSumOfSumFTEYr5).setScale(4);
            sol.PyramidRichnessY6__c  = (solPyr.effSumOfSumFTEYr6==0)?0: (solPyr.sumOfSumFTEYr6/ solPyr.effSumOfSumFTEYr6).setScale(4);
            sol.PyramidRichnessY7__c  = (solPyr.effSumOfSumFTEYr7==0)?0: (solPyr.sumOfSumFTEYr7/ solPyr.effSumOfSumFTEYr7).setScale(4);
            sol.PyramidRichnessY8__c  = (solPyr.effSumOfSumFTEYr8==0)?0: (solPyr.sumOfSumFTEYr8/ solPyr.effSumOfSumFTEYr8).setScale(4);
            sol.PyramidRichnessY9__c  = (solPyr.effSumOfSumFTEYr9==0)?0: (solPyr.sumOfSumFTEYr9/ solPyr.effSumOfSumFTEYr9).setScale(4);
            sol.PyramidRichnessY10__c  = (solPyr.effSumOfSumFTEYr10==0)?0: (solPyr.sumOfSumFTEYr10/ solPyr.effSumOfSumFTEYr10).setScale(4);
            
            sol.Cost_Per_FTE_Y1__c = (solPyr.sumOfFteYr1==0)?0: (solPyr.sumOfRunYr1/ solPyr.sumOfFteYr1).setScale(4);
            sol.Cost_Per_FTE_Y2__c = (solPyr.sumOfFteYr2==0)?0: (solPyr.sumOfRunYr2/ solPyr.sumOfFteYr2).setScale(4);
            sol.Cost_Per_FTE_Y3__c = (solPyr.sumOfFteYr3==0)?0: (solPyr.sumOfRunYr3/ solPyr.sumOfFteYr3).setScale(4);
            sol.Cost_Per_FTE_Y4__c = (solPyr.sumOfFteYr4==0)?0: (solPyr.sumOfRunYr4/ solPyr.sumOfFteYr4).setScale(4);
            sol.Cost_Per_FTE_Y5__c = (solPyr.sumOfFteYr5==0)?0: (solPyr.sumOfRunYr5/ solPyr.sumOfFteYr5).setScale(4);
            sol.Cost_Per_FTE_Y6__c = (solPyr.sumOfFteYr6==0)?0: (solPyr.sumOfRunYr6/ solPyr.sumOfFteYr6).setScale(4);
            sol.Cost_Per_FTE_Y7__c = (solPyr.sumOfFteYr7==0)?0: (solPyr.sumOfRunYr7/ solPyr.sumOfFteYr7).setScale(4);
            sol.Cost_Per_FTE_Y8__c = (solPyr.sumOfFteYr8==0)?0: (solPyr.sumOfRunYr8/ solPyr.sumOfFteYr8).setScale(4);
            sol.Cost_Per_FTE_Y9__c = (solPyr.sumOfFteYr9==0)?0: (solPyr.sumOfRunYr9/ solPyr.sumOfFteYr9).setScale(4);
            sol.Cost_Per_FTE_Y10__c = (solPyr.sumOfFteYr10==0)?0: (solPyr.sumOfRunYr10/ solPyr.sumOfFteYr10).setScale(4);
            
            
            oppWrap.sumOfSumFTEYr1+=solPyr.sumOfSumFTEYr1;
            oppWrap.sumOfSumFTEYr2+=solPyr.sumOfSumFTEYr2;
            oppWrap.sumOfSumFTEYr3+=solPyr.sumOfSumFTEYr3;
            oppWrap.sumOfSumFTEYr4+=solPyr.sumOfSumFTEYr4;
            oppWrap.sumOfSumFTEYr5+=solPyr.sumOfSumFTEYr5;
            oppWrap.sumOfSumFTEYr6+=solPyr.sumOfSumFTEYr6;
            oppWrap.sumOfSumFTEYr7+=solPyr.sumOfSumFTEYr7;
            oppWrap.sumOfSumFTEYr8+=solPyr.sumOfSumFTEYr8;
            oppWrap.sumOfSumFTEYr9+=solPyr.sumOfSumFTEYr9;
            oppWrap.sumOfSumFTEYr10+=solPyr.sumOfSumFTEYr10;
            oppWrap.effSumOfSumFTEYr1+=solPyr.effsumOfSumFTEYr1;
            oppWrap.effsumOfSumFTEYr2+=solPyr.effsumOfSumFTEYr2;
            oppWrap.effsumOfSumFTEYr3+=solPyr.effsumOfSumFTEYr3;
            oppWrap.effsumOfSumFTEYr4+=solPyr.effsumOfSumFTEYr4;
            oppWrap.effsumOfSumFTEYr5+=solPyr.effsumOfSumFTEYr5;
            oppWrap.effsumOfSumFTEYr6+=solPyr.effsumOfSumFTEYr6;
            oppWrap.effsumOfSumFTEYr7+=solPyr.effsumOfSumFTEYr7;
            oppWrap.effsumOfSumFTEYr8+=solPyr.effsumOfSumFTEYr8;
            oppWrap.effsumOfSumFTEYr9+=solPyr.effsumOfSumFTEYr9;
            oppWrap.effsumOfSumFTEYr10+=solPyr.effsumOfSumFTEYr10;
               
                oppWrap.sumOfRunYr1+= solPyr.sumOfRunYr1;
                oppWrap.sumOfRunYr2+= solPyr.sumOfRunYr2;
                oppWrap.sumOfRunYr3+= solPyr.sumOfRunYr3;
                oppWrap.sumOfRunYr4+= solPyr.sumOfRunYr4;
                oppWrap.sumOfRunYr5+= solPyr.sumOfRunYr5;
                oppWrap.sumOfRunYr6+= solPyr.sumOfRunYr6;
                oppWrap.sumOfRunYr7+= solPyr.sumOfRunYr7;
                oppWrap.sumOfRunYr8+= solPyr.sumOfRunYr8;
                oppWrap.sumOfRunYr9+= solPyr.sumOfRunYr9;
                oppWrap.sumOfRunYr10+= solPyr.sumOfRunYr10;
                oppWrap.sumOfFteYr1+= solPyr.sumOfFteYr1;
                oppWrap.sumOfFteYr2+= solPyr.sumOfFteYr2;
                oppWrap.sumOfFteYr3+= solPyr.sumOfFteYr3;
                oppWrap.sumOfFteYr4+= solPyr.sumOfFteYr4;
                oppWrap.sumOfFteYr5+= solPyr.sumOfFteYr5;
                oppWrap.sumOfFteYr6+= solPyr.sumOfFteYr6;
                oppWrap.sumOfFteYr7+= solPyr.sumOfFteYr7;
                oppWrap.sumOfFteYr8+= solPyr.sumOfFteYr8;
                oppWrap.sumOfFteYr9+= solPyr.sumOfFteYr9;
                oppWrap.sumOfFteYr10+= solPyr.sumOfFteYr10;

            //solPyr = new PyramidRichnessWrapper();
            }
            System.debug('SolPr ' + solPyr );
            System.debug('sol>>????' + sol.Name + '==' + sol);
            
        }
        
            opp.PyramidRichnessY1__c  = (oppWrap.effSumOfSumFTEYr1==0)?0: (oppWrap.sumOfSumFTEYr1/ oppWrap.effSumOfSumFTEYr1).setScale(4);
            opp.PyramidRichnessY2__c  = (oppWrap.effSumOfSumFTEYr2==0)?0: (oppWrap.sumOfSumFTEYr2/ oppWrap.effSumOfSumFTEYr2).setScale(4);
            opp.PyramidRichnessY3__c  = (oppWrap.effSumOfSumFTEYr3==0)?0: (oppWrap.sumOfSumFTEYr3/ oppWrap.effSumOfSumFTEYr3).setScale(4);
            opp.PyramidRichnessY4__c  = (oppWrap.effSumOfSumFTEYr4==0)?0: (oppWrap.sumOfSumFTEYr4/ oppWrap.effSumOfSumFTEYr4).setScale(4);
            opp.PyramidRichnessY5__c  = (oppWrap.effSumOfSumFTEYr5==0)?0: (oppWrap.sumOfSumFTEYr5/ oppWrap.effSumOfSumFTEYr5).setScale(4);
            opp.PyramidRichnessY6__c  = (oppWrap.effSumOfSumFTEYr6==0)?0: (oppWrap.sumOfSumFTEYr6/ oppWrap.effSumOfSumFTEYr6).setScale(4);
            opp.PyramidRichnessY7__c  = (oppWrap.effSumOfSumFTEYr7==0)?0: (oppWrap.sumOfSumFTEYr7/ oppWrap.effSumOfSumFTEYr7).setScale(4);
            opp.PyramidRichnessY8__c  = (oppWrap.effSumOfSumFTEYr8==0)?0: (oppWrap.sumOfSumFTEYr8/ oppWrap.effSumOfSumFTEYr8).setScale(4);
            opp.PyramidRichnessY9__c  = (oppWrap.effSumOfSumFTEYr9==0)?0: (oppWrap.sumOfSumFTEYr9/ oppWrap.effSumOfSumFTEYr9).setScale(4);
            opp.PyramidRichnessY10__c  = (oppWrap.effSumOfSumFTEYr10==0)?0: (oppWrap.sumOfSumFTEYr10/ oppWrap.effSumOfSumFTEYr10).setScale(4);
            
            //System.debug('Opp>>> ' + opp);
            
            opp.Cost_Per_FTE_Y1__c = (oppWrap.sumOfFteYr1==0)?0: (oppWrap.sumOfRunYr1/ oppWrap.sumOfFteYr1).setScale(4);
            opp.Cost_Per_FTE_Y2__c = (oppWrap.sumOfFteYr2==0)?0: (oppWrap.sumOfRunYr2/ oppWrap.sumOfFteYr2).setScale(4);
            opp.Cost_Per_FTE_Y3__c = (oppWrap.sumOfFteYr3==0)?0: (oppWrap.sumOfRunYr3/ oppWrap.sumOfFteYr3).setScale(4);
            opp.Cost_Per_FTE_Y4__c = (oppWrap.sumOfFteYr4==0)?0: (oppWrap.sumOfRunYr4/ oppWrap.sumOfFteYr4).setScale(4);
            opp.Cost_Per_FTE_Y5__c = (oppWrap.sumOfFteYr5==0)?0: (oppWrap.sumOfRunYr5/ oppWrap.sumOfFteYr5).setScale(4);
            opp.Cost_Per_FTE_Y6__c = (oppWrap.sumOfFteYr6==0)?0: (oppWrap.sumOfRunYr6/ oppWrap.sumOfFteYr6).setScale(4);
            opp.Cost_Per_FTE_Y7__c = (oppWrap.sumOfFteYr7==0)?0: (oppWrap.sumOfRunYr7/ oppWrap.sumOfFteYr7).setScale(4);
            opp.Cost_Per_FTE_Y8__c = (oppWrap.sumOfFteYr8==0)?0: (oppWrap.sumOfRunYr8/ oppWrap.sumOfFteYr8).setScale(4);
            opp.Cost_Per_FTE_Y9__c = (oppWrap.sumOfFteYr9==0)?0: (oppWrap.sumOfRunYr9/ oppWrap.sumOfFteYr9).setScale(4);
            opp.Cost_Per_FTE_Y10__c = (oppWrap.sumOfFteYr10==0)?0: (oppWrap.sumOfRunYr10/ oppWrap.sumOfFteYr10).setScale(4);
        
    //update serviceList; 
    //update solutionList;
        System.debug('opp >>>>>' + opp);
    }
    catch(Exception e){
        ExceptionClass.logException('PyramindRichness_V2', 'PyramindRichness_V2' , e, 'MobWorkbench','MobWorkbench');
    }
       
    }
    
    
    public static void delLocPyrRichnessCalc(Set<Id> nFTEIds, List<Opportunity_Delivery_Location__c> delLocList){
       
      List<FTE_Details__c> inputFTEDetail = [SELECT Career_Level__r.Name, Opportunity_Delivery_Location__c, Service__r.Services__r.name,Sub_Service_Group__r.Offering_Master__r.name,
                                        Career_Level__c,Costing_Type__c,Opportunity__c,Sub_Service_Group__c,Sub_Service_Group__r.Name,
                                        Service_Component_Name__c,Service_Component__c,Service_Group__c,
                                        Service_Name__c,Service__c,Service__r.Serv_Nm__c,Sub_Service_Group_Name__c,
                                        Mob_Totals__c,FTEYr1__c,FTEYr2__c,FTEYr3__c,FTEYr4__c,FTEYr5__c,FTEYr6__c,FTEYr7__c,
                                        FTEYr8__c,FTEYr9__c,FTEYr10__c,FTEMobTotals__c,Delivery_Location__r.Name,
                                        Run_Yr1__c,Run_Yr2__c,Run_Yr3__c,Run_Yr4__c,Run_Yr5__c,Run_Yr6__c,Run_Yr7__c,Run_Yr8__c,Run_Yr9__c,Run_Yr10__c,
                                        Opportunity_Delivery_Location__r.Delivery_Location__r.name,Costing_Request__r.Opportunity__c,Service__r.Delivery_Locations__c 
                                        FROM FTE_Details__c WHERE ID IN :nFTEids  LIMIT 10000];
                                
   
    Map<Id, PyramidRichnessWrapper> oppDLocMap =  new Map<Id, PyramidRichnessWrapper>();
    //PyramidRichnessWrapper svcPyrWrap ;
    PyramidRichnessWrapper oppDelWrap;  
        
     for(FTE_Details__c fterec: inputFTEDetail){
        
        System.debug('fteRec details>> ' + fteRec.Opportunity_Delivery_Location__c + '' + fteRec.Id);

        
        if(fterec.Opportunity_Delivery_Location__c <> null){
        
            PyramidRichnessWrapper dLocWrap= new PyramidRichnessWrapper ();
            System.debug('dLocWrap '  +dLocWrap);
            if(!oppDLocMap.containsKey(fterec.Opportunity_Delivery_Location__c)){
                dLocWrap.serviceId = fterec.service__c;
                dLocWrap.solutionId = fteRec.Sub_Service_Group__c;
                dLocWrap.oppDelocID = fteRec.Opportunity_Delivery_Location__c;
            }
            else{
                //dLocWrap= new PyramidRichnessWrapper ();
                dLocWrap = oppDLocMap.get(fterec.Opportunity_Delivery_Location__c);
            }
           // System.debug('oppDLocMap ???' + oppDLocMap );
            dLocWrap.sumOfRunYr1+= fterec.Run_Yr1__c;
            dLocWrap.sumOfRunYr2+= fterec.Run_Yr2__c;
            dLocWrap.sumOfRunYr3+= fterec.Run_Yr3__c;
            dLocWrap.sumOfRunYr4+= fterec.Run_Yr4__c;
            dLocWrap.sumOfRunYr5+= fterec.Run_Yr5__c;
            dLocWrap.sumOfRunYr6+= fterec.Run_Yr6__c;
            dLocWrap.sumOfRunYr7+= fterec.Run_Yr7__c;
            dLocWrap.sumOfRunYr8+= fterec.Run_Yr8__c;
            dLocWrap.sumOfRunYr9+= fterec.Run_Yr9__c;
            dLocWrap.sumOfRunYr10+= fterec.Run_Yr10__c;
            dLocWrap.sumOfFteYr1+= fterec.FteYr1__c;
            dLocWrap.sumOfFteYr2+= fterec.FteYr2__c;
            dLocWrap.sumOfFteYr3+= fterec.FteYr3__c;
            dLocWrap.sumOfFteYr4+= fterec.FteYr4__c;
            dLocWrap.sumOfFteYr5+= fterec.FteYr5__c;
            dLocWrap.sumOfFteYr6+= fterec.FteYr6__c;
            dLocWrap.sumOfFteYr7+= fterec.FteYr7__c;
            dLocWrap.sumOfFteYr8+= fterec.FteYr8__c;
            dLocWrap.sumOfFteYr9+= fterec.FteYr9__c;
            dLocWrap.sumOfFteYr10+= fterec.FteYr10__c;

        
            if(UtilConstants.SDO.equalsIgnoreCase(fterec.Costing_Type__c)  ){
            //System.debug('>>>>>>> ' + dLocWrap);
            //calculation for pyramid richness
                    if(UtilConstants.ASSOCIATE13.equalsIgnoreCase(fterec.Career_Level__r.Name)){
                        dLocWrap.sumOfFteYr1Lvl1+= fterec.FTEYr1__c;
                        dLocWrap.sumOfFteYr2Lvl1+= fterec.FTEYr2__c;
                        dLocWrap.sumOfFteYr3Lvl1+= fterec.FTEYr3__c;
                        dLocWrap.sumOfFteYr4Lvl1+= fterec.FTEYr4__c;
                        dLocWrap.sumOfFteYr5Lvl1+= fterec.FTEYr5__c;
                        dLocWrap.sumOfFteYr6Lvl1+= fterec.FTEYr6__c;
                        dLocWrap.sumOfFteYr7Lvl1+= fterec.FTEYr7__c;
                        dLocWrap.sumOfFteYr8Lvl1+= fterec.FTEYr8__c;
                        dLocWrap.sumOfFteYr9Lvl1+= fterec.FTEYr9__c;
                        dLocWrap.sumOfFteYr10Lvl1+=fterec.FTEYr10__c;
                    }else if(UtilConstants.ASSOCIATE12.equalsIgnoreCase(fterec.Career_Level__r.Name)){
                        dLocWrap.sumOfFteYr1Lvl2+= fterec.FTEYr1__c;
                        dLocWrap.sumOfFteYr2Lvl2+= fterec.FTEYr2__c;
                        dLocWrap.sumOfFteYr3Lvl2+= fterec.FTEYr3__c;
                        dLocWrap.sumOfFteYr4Lvl2+= fterec.FTEYr4__c;
                        dLocWrap.sumOfFteYr5Lvl2+= fterec.FTEYr5__c;
                        dLocWrap.sumOfFteYr6Lvl2+= fterec.FTEYr6__c;
                        dLocWrap.sumOfFteYr7Lvl2+= fterec.FTEYr7__c;
                        dLocWrap.sumOfFteYr8Lvl2+= fterec.FTEYr8__c;
                        dLocWrap.sumOfFteYr9Lvl2+= fterec.FTEYr9__c;
                        dLocWrap.sumOfFteYr10Lvl2+=fterec.FTEYr10__c;
                    }else if(UtilConstants.ANALYST11.equalsIgnoreCase(fterec.Career_Level__r.Name)){
                        dLocWrap.sumOfFteYr1Lvl3+= fterec.FTEYr1__c;
                        dLocWrap.sumOfFteYr2Lvl3+= fterec.FTEYr2__c;
                        dLocWrap.sumOfFteYr3Lvl3+= fterec.FTEYr3__c;
                        dLocWrap.sumOfFteYr4Lvl3+= fterec.FTEYr4__c;
                        dLocWrap.sumOfFteYr5Lvl3+= fterec.FTEYr5__c;
                        dLocWrap.sumOfFteYr6Lvl3+= fterec.FTEYr6__c;
                        dLocWrap.sumOfFteYr7Lvl3+= fterec.FTEYr7__c;
                        dLocWrap.sumOfFteYr8Lvl3+= fterec.FTEYr8__c;
                        dLocWrap.sumOfFteYr9Lvl3+= fterec.FTEYr9__c;
                        dLocWrap.sumOfFteYr10Lvl3+=fterec.FTEYr10__c;
                    }else if(UtilConstants.ANALYST10.equalsIgnoreCase(fterec.Career_Level__r.Name)){
                        dLocWrap.sumOfFteYr1Lvl4+= fterec.FTEYr1__c;
                        dLocWrap.sumOfFteYr2Lvl4+= fterec.FTEYr2__c;
                        dLocWrap.sumOfFteYr3Lvl4+= fterec.FTEYr3__c;
                        dLocWrap.sumOfFteYr4Lvl4+= fterec.FTEYr4__c;
                        dLocWrap.sumOfFteYr5Lvl4+= fterec.FTEYr5__c;
                        dLocWrap.sumOfFteYr6Lvl4+= fterec.FTEYr6__c;
                        dLocWrap.sumOfFteYr7Lvl4+= fterec.FTEYr7__c;
                        dLocWrap.sumOfFteYr8Lvl4+= fterec.FTEYr8__c;
                        dLocWrap.sumOfFteYr9Lvl4+= fterec.FTEYr9__c;
                        dLocWrap.sumOfFteYr10Lvl4+=fterec.FTEYr10__c;
                    }else if(UtilConstants.CONSULTANT9.equalsIgnoreCase(fterec.Career_Level__r.Name)){
                        dLocWrap.sumOfFteYr1Lvl5+= fterec.FTEYr1__c;
                        dLocWrap.sumOfFteYr2Lvl5+= fterec.FTEYr2__c;
                        dLocWrap.sumOfFteYr3Lvl5+= fterec.FTEYr3__c;
                        dLocWrap.sumOfFteYr4Lvl5+= fterec.FTEYr4__c;
                        dLocWrap.sumOfFteYr5Lvl5+= fterec.FTEYr5__c;
                        dLocWrap.sumOfFteYr6Lvl5+= fterec.FTEYr6__c;
                        dLocWrap.sumOfFteYr7Lvl5+= fterec.FTEYr7__c;
                        dLocWrap.sumOfFteYr8Lvl5+= fterec.FTEYr8__c;
                        dLocWrap.sumOfFteYr9Lvl5+= fterec.FTEYr9__c;
                        dLocWrap.sumOfFteYr10Lvl5+=fterec.FTEYr10__c;
                    }else if(UtilConstants.CONSULTANT8.equalsIgnoreCase(fterec.Career_Level__r.Name)){
                        dLocWrap.sumOfFteYr1Lvl6+= fterec.FTEYr1__c;
                        dLocWrap.sumOfFteYr2Lvl6+= fterec.FTEYr2__c;
                        dLocWrap.sumOfFteYr3Lvl6+= fterec.FTEYr3__c;
                        dLocWrap.sumOfFteYr4Lvl6+= fterec.FTEYr4__c;
                        dLocWrap.sumOfFteYr5Lvl6+= fterec.FTEYr5__c;
                        dLocWrap.sumOfFteYr6Lvl6+= fterec.FTEYr6__c;
                        dLocWrap.sumOfFteYr7Lvl6+= fterec.FTEYr7__c;
                        dLocWrap.sumOfFteYr8Lvl6+= fterec.FTEYr8__c;
                        dLocWrap.sumOfFteYr9Lvl6+= fterec.FTEYr9__c;
                        dLocWrap.sumOfFteYr10Lvl6+=fterec.FTEYr10__c;
                    }else if(UtilConstants.MANAGER7.equalsIgnoreCase(fterec.Career_Level__r.Name)){
                        dLocWrap.sumOfFteYr1Lvl7+= fterec.FTEYr1__c;
                        dLocWrap.sumOfFteYr2Lvl7+= fterec.FTEYr2__c;
                        dLocWrap.sumOfFteYr3Lvl7+= fterec.FTEYr3__c;
                        dLocWrap.sumOfFteYr4Lvl7+= fterec.FTEYr4__c;
                        dLocWrap.sumOfFteYr5Lvl7+= fterec.FTEYr5__c;
                        dLocWrap.sumOfFteYr6Lvl7+= fterec.FTEYr6__c;
                        dLocWrap.sumOfFteYr7Lvl7+= fterec.FTEYr7__c;
                        dLocWrap.sumOfFteYr8Lvl7+= fterec.FTEYr8__c;
                        dLocWrap.sumOfFteYr9Lvl7+= fterec.FTEYr9__c;
                        dLocWrap.sumOfFteYr10Lvl7+=fterec.FTEYr10__c;
                    }else if(UtilConstants.SENIORMANAGER6.equalsIgnoreCase(fterec.Career_Level__r.Name) || UtilConstants.SENIORMANAGER5.equalsIgnoreCase(fterec.Career_Level__r.Name)){
                        dLocWrap.sumOfFteYr1Lvl8+= fterec.FTEYr1__c;
                        dLocWrap.sumOfFteYr2Lvl8+= fterec.FTEYr2__c;
                        dLocWrap.sumOfFteYr3Lvl8+= fterec.FTEYr3__c;
                        dLocWrap.sumOfFteYr4Lvl8+= fterec.FTEYr4__c;
                        dLocWrap.sumOfFteYr5Lvl8+= fterec.FTEYr5__c;
                        dLocWrap.sumOfFteYr6Lvl8+= fterec.FTEYr6__c;
                        dLocWrap.sumOfFteYr7Lvl8+= fterec.FTEYr7__c;
                        dLocWrap.sumOfFteYr8Lvl8+= fterec.FTEYr8__c;
                        dLocWrap.sumOfFteYr9Lvl8+= fterec.FTEYr9__c;
                        dLocWrap.sumOfFteYr10Lvl8+=fterec.FTEYr10__c;
                    }else{ } 
           }
           
           oppDLocMap.put(fteRec.Opportunity_Delivery_Location__c, dLocWrap);
        }
           
    }
    
      
    //System.debug('oppDLocMap>>>> ' + oppDLocMap);
    System.debug('oppDLOcMap>>>> sixe ' + oppDLOcMap.size());
    PyramidRichnessWrapper svcWrap;
    PyramidRichnessWrapper dLocWrap = new PyramidRichnessWrapper();
    
    
    for(Opportunity_Delivery_Location__c delLoc : delLocList){
        
        
        oppDelWrap= new PyramidRichnessWrapper();
        if(oppDLocMap.containsKey(delLoc.Id)){
            oppDelWrap= oppDLocMap.get(delLoc.Id);
            
            oppDelWrap.sumOfSumFTEYr1 = oppDelWrap.sumOfFteYr1Lvl1 + oppDelWrap.sumOfFteYr1Lvl2 + oppDelWrap.sumOfFteYr1Lvl3 + oppDelWrap.sumOfFteYr1Lvl4 + oppDelWrap.sumOfFteYr1Lvl5 + oppDelWrap.sumOfFteYr1Lvl6 + oppDelWrap.sumOfFteYr1Lvl7 + oppDelWrap.sumOfFteYr1Lvl8;
            oppDelWrap.effSumOfSumFTEYr1 = oppDelWrap.sumOfFteYr1Lvl1*1 + oppDelWrap.sumOfFteYr1Lvl2*2 + oppDelWrap.sumOfFteYr1Lvl3*3 + oppDelWrap.sumOfFteYr1Lvl4*4 + oppDelWrap.sumOfFteYr1Lvl5*5 + oppDelWrap.sumOfFteYr1Lvl6*6 + oppDelWrap.sumOfFteYr1Lvl7*7 + oppDelWrap.sumOfFteYr1Lvl8*8;
            delLoc.PyramidRichnessY1__c = (oppDelWrap.effSumOfSumFTEYr1==0)? 0 : (oppDelWrap.sumOfSumFTEYr1/ oppDelWrap.effSumOfSumFTEYr1).setScale(4);
            
            oppDelWrap.sumOfSumFTEYr2 = oppDelWrap.sumOfFteYr2Lvl1 + oppDelWrap.sumOfFteYr2Lvl2 + oppDelWrap.sumOfFteYr2Lvl3 + oppDelWrap.sumOfFteYr2Lvl4 + oppDelWrap.sumOfFteYr2Lvl5 + oppDelWrap.sumOfFteYr2Lvl6 + oppDelWrap.sumOfFteYr2Lvl7 + oppDelWrap.sumOfFteYr2Lvl8;
            oppDelWrap.effSumOfSumFTEYr2 = oppDelWrap.sumOfFteYr2Lvl1*1 + oppDelWrap.sumOfFteYr2Lvl2*2 + oppDelWrap.sumOfFteYr2Lvl3*3 + oppDelWrap.sumOfFteYr2Lvl4*4 + oppDelWrap.sumOfFteYr2Lvl5*5 + oppDelWrap.sumOfFteYr2Lvl6*6 + oppDelWrap.sumOfFteYr2Lvl7*7 + oppDelWrap.sumOfFteYr2Lvl8*8;
            delLoc.PyramidRichnessY2__c = (oppDelWrap.effSumOfSumFTEYr2==0)? 0 : (oppDelWrap.sumOfSumFTEYr2/ oppDelWrap.effSumOfSumFTEYr2).setScale(4);
            
            oppDelWrap.sumOfSumFTEYr3 = oppDelWrap.sumOfFteYr3Lvl1 + oppDelWrap.sumOfFteYr3Lvl2 + oppDelWrap.sumOfFteYr3Lvl3 + oppDelWrap.sumOfFteYr3Lvl4 + oppDelWrap.sumOfFteYr3Lvl5 + oppDelWrap.sumOfFteYr3Lvl6 + oppDelWrap.sumOfFteYr3Lvl7 + oppDelWrap.sumOfFteYr3Lvl8;
            oppDelWrap.effSumOfSumFTEYr3 = oppDelWrap.sumOfFteYr3Lvl1*1 + oppDelWrap.sumOfFteYr3Lvl2*2 + oppDelWrap.sumOfFteYr3Lvl3*3 + oppDelWrap.sumOfFteYr3Lvl4*4 + oppDelWrap.sumOfFteYr3Lvl5*5 + oppDelWrap.sumOfFteYr3Lvl6*6 + oppDelWrap.sumOfFteYr3Lvl7*7 + oppDelWrap.sumOfFteYr3Lvl8*8;
            delLoc.PyramidRichnessY3__c = (oppDelWrap.effSumOfSumFTEYr3==0)? 0 : (oppDelWrap.sumOfSumFTEYr3/ oppDelWrap.effSumOfSumFTEYr3).setScale(4);
            
            oppDelWrap.sumOfSumFTEYr4 = oppDelWrap.sumOfFteYr4Lvl1 + oppDelWrap.sumOfFteYr4Lvl2 + oppDelWrap.sumOfFteYr4Lvl3 + oppDelWrap.sumOfFteYr4Lvl4 + oppDelWrap.sumOfFteYr4Lvl5 + oppDelWrap.sumOfFteYr4Lvl6 + oppDelWrap.sumOfFteYr4Lvl7 + oppDelWrap.sumOfFteYr4Lvl8;
            oppDelWrap.effSumOfSumFTEYr4 = oppDelWrap.sumOfFteYr4Lvl1*1 + oppDelWrap.sumOfFteYr4Lvl2*2 + oppDelWrap.sumOfFteYr4Lvl3*3 + oppDelWrap.sumOfFteYr4Lvl4*4 + oppDelWrap.sumOfFteYr4Lvl5*5 + oppDelWrap.sumOfFteYr4Lvl6*6 + oppDelWrap.sumOfFteYr4Lvl7*7 + oppDelWrap.sumOfFteYr4Lvl8*8;
            delLoc.PyramidRichnessY4__c = (oppDelWrap.effSumOfSumFTEYr4==0)? 0 : (oppDelWrap.sumOfSumFTEYr4/ oppDelWrap.effSumOfSumFTEYr4).setScale(4);
            
            oppDelWrap.sumOfSumFTEYr5 = oppDelWrap.sumOfFteYr5Lvl1 + oppDelWrap.sumOfFteYr5Lvl2 + oppDelWrap.sumOfFteYr5Lvl3 + oppDelWrap.sumOfFteYr5Lvl4 + oppDelWrap.sumOfFteYr5Lvl5 + oppDelWrap.sumOfFteYr5Lvl6 + oppDelWrap.sumOfFteYr5Lvl7 + oppDelWrap.sumOfFteYr5Lvl8;
            oppDelWrap.effSumOfSumFTEYr5 = oppDelWrap.sumOfFteYr5Lvl1*1 + oppDelWrap.sumOfFteYr5Lvl2*2 + oppDelWrap.sumOfFteYr5Lvl3*3 + oppDelWrap.sumOfFteYr5Lvl4*4 + oppDelWrap.sumOfFteYr5Lvl5*5 + oppDelWrap.sumOfFteYr5Lvl6*6 + oppDelWrap.sumOfFteYr5Lvl7*7 + oppDelWrap.sumOfFteYr5Lvl8*8;
            delLoc.PyramidRichnessY5__c = (oppDelWrap.effSumOfSumFTEYr5==0)? 0 : (oppDelWrap.sumOfSumFTEYr5/ oppDelWrap.effSumOfSumFTEYr5).setScale(4);
            
            oppDelWrap.sumOfSumFTEYr6 = oppDelWrap.sumOfFteYr6Lvl1 + oppDelWrap.sumOfFteYr6Lvl2 + oppDelWrap.sumOfFteYr6Lvl3 + oppDelWrap.sumOfFteYr6Lvl4 + oppDelWrap.sumOfFteYr6Lvl5 + oppDelWrap.sumOfFteYr6Lvl6 + oppDelWrap.sumOfFteYr6Lvl7 + oppDelWrap.sumOfFteYr6Lvl8;
            oppDelWrap.effSumOfSumFTEYr6 = oppDelWrap.sumOfFteYr6Lvl1*1 + oppDelWrap.sumOfFteYr6Lvl2*2 + oppDelWrap.sumOfFteYr6Lvl3*3 + oppDelWrap.sumOfFteYr6Lvl4*4 + oppDelWrap.sumOfFteYr6Lvl5*5 + oppDelWrap.sumOfFteYr6Lvl6*6 + oppDelWrap.sumOfFteYr6Lvl7*7 + oppDelWrap.sumOfFteYr6Lvl8*8;
            delLoc.PyramidRichnessY6__c = (oppDelWrap.effSumOfSumFTEYr6==0)? 0 : (oppDelWrap.sumOfSumFTEYr6/ oppDelWrap.effSumOfSumFTEYr6).setScale(4);
            
            oppDelWrap.sumOfSumFTEYr7 = oppDelWrap.sumOfFteYr7Lvl1 + oppDelWrap.sumOfFteYr7Lvl2 + oppDelWrap.sumOfFteYr7Lvl3 + oppDelWrap.sumOfFteYr7Lvl4 + oppDelWrap.sumOfFteYr7Lvl5 + oppDelWrap.sumOfFteYr7Lvl6 + oppDelWrap.sumOfFteYr7Lvl7 + oppDelWrap.sumOfFteYr7Lvl8;
            oppDelWrap.effSumOfSumFTEYr7 = oppDelWrap.sumOfFteYr7Lvl1*1 + oppDelWrap.sumOfFteYr7Lvl2*2 + oppDelWrap.sumOfFteYr7Lvl3*3 + oppDelWrap.sumOfFteYr7Lvl4*4 + oppDelWrap.sumOfFteYr7Lvl5*5 + oppDelWrap.sumOfFteYr7Lvl6*6 + oppDelWrap.sumOfFteYr7Lvl7*7 + oppDelWrap.sumOfFteYr7Lvl8*8;
            delLoc.PyramidRichnessY7__c = (oppDelWrap.effSumOfSumFTEYr7==0)? 0 : (oppDelWrap.sumOfSumFTEYr7/ oppDelWrap.effSumOfSumFTEYr7).setScale(4);
            
            oppDelWrap.sumOfSumFTEYr8 = oppDelWrap.sumOfFteYr8Lvl1 + oppDelWrap.sumOfFteYr8Lvl2 + oppDelWrap.sumOfFteYr8Lvl3 + oppDelWrap.sumOfFteYr8Lvl4 + oppDelWrap.sumOfFteYr8Lvl5 + oppDelWrap.sumOfFteYr8Lvl6 + oppDelWrap.sumOfFteYr8Lvl7 + oppDelWrap.sumOfFteYr8Lvl8;
            oppDelWrap.effSumOfSumFTEYr8 = oppDelWrap.sumOfFteYr8Lvl1*1 + oppDelWrap.sumOfFteYr8Lvl2*2 + oppDelWrap.sumOfFteYr8Lvl3*3 + oppDelWrap.sumOfFteYr8Lvl4*4 + oppDelWrap.sumOfFteYr8Lvl5*5 + oppDelWrap.sumOfFteYr8Lvl6*6 + oppDelWrap.sumOfFteYr8Lvl7*7 + oppDelWrap.sumOfFteYr8Lvl8*8;
            delLoc.PyramidRichnessY8__c = (oppDelWrap.effSumOfSumFTEYr8==0)? 0 : (oppDelWrap.sumOfSumFTEYr8/ oppDelWrap.effSumOfSumFTEYr8).setScale(4);
            
            oppDelWrap.sumOfSumFTEYr9 = oppDelWrap.sumOfFteYr9Lvl1 + oppDelWrap.sumOfFteYr9Lvl2 + oppDelWrap.sumOfFteYr9Lvl3 + oppDelWrap.sumOfFteYr9Lvl4 + oppDelWrap.sumOfFteYr9Lvl5 + oppDelWrap.sumOfFteYr9Lvl6 + oppDelWrap.sumOfFteYr9Lvl7 + oppDelWrap.sumOfFteYr9Lvl8;
            oppDelWrap.effSumOfSumFTEYr9 = oppDelWrap.sumOfFteYr9Lvl1*1 + oppDelWrap.sumOfFteYr9Lvl2*2 + oppDelWrap.sumOfFteYr9Lvl3*3 + oppDelWrap.sumOfFteYr9Lvl4*4 + oppDelWrap.sumOfFteYr9Lvl5*5 + oppDelWrap.sumOfFteYr9Lvl6*6 + oppDelWrap.sumOfFteYr9Lvl7*7 + oppDelWrap.sumOfFteYr9Lvl8*8;
            delLoc.PyramidRichnessY9__c = (oppDelWrap.effSumOfSumFTEYr9==0)? 0 : (oppDelWrap.sumOfSumFTEYr9/ oppDelWrap.effSumOfSumFTEYr9).setScale(4);
            
            oppDelWrap.sumOfSumFTEYr10 = oppDelWrap.sumOfFteYr10Lvl1 + oppDelWrap.sumOfFteYr10Lvl2 + oppDelWrap.sumOfFteYr10Lvl3 + oppDelWrap.sumOfFteYr10Lvl4 + oppDelWrap.sumOfFteYr10Lvl5 + oppDelWrap.sumOfFteYr10Lvl6 + oppDelWrap.sumOfFteYr10Lvl7 + oppDelWrap.sumOfFteYr10Lvl8;
            oppDelWrap.effSumOfSumFTEYr10 = oppDelWrap.sumOfFteYr10Lvl1*1 + oppDelWrap.sumOfFteYr10Lvl2*2 + oppDelWrap.sumOfFteYr10Lvl3*3 + oppDelWrap.sumOfFteYr10Lvl4*4 + oppDelWrap.sumOfFteYr10Lvl5*5 + oppDelWrap.sumOfFteYr10Lvl6*6 + oppDelWrap.sumOfFteYr10Lvl7*7 + oppDelWrap.sumOfFteYr10Lvl8*8;
            delLoc.PyramidRichnessY10__c = (oppDelWrap.effSumOfSumFTEYr10==0)? 0 : (oppDelWrap.sumOfSumFTEYr10/ oppDelWrap.effSumOfSumFTEYr10).setScale(4);
            
            
            delLoc.Cost_Per_FTE_Y1__c = (oppDelWrap.sumOfFteYr1==0)?0: (oppDelWrap.sumOfRunYr1/ oppDelWrap.sumOfFteYr1).setScale(4);
            delLoc.Cost_Per_FTE_Y2__c = (oppDelWrap.sumOfFteYr2==0)?0: (oppDelWrap.sumOfRunYr2/ oppDelWrap.sumOfFteYr2).setScale(4);
            delLoc.Cost_Per_FTE_Y3__c = (oppDelWrap.sumOfFteYr3==0)?0: (oppDelWrap.sumOfRunYr3/ oppDelWrap.sumOfFteYr3).setScale(4);
            delLoc.Cost_Per_FTE_Y4__c = (oppDelWrap.sumOfFteYr4==0)?0: (oppDelWrap.sumOfRunYr4/ oppDelWrap.sumOfFteYr4).setScale(4);
            delLoc.Cost_Per_FTE_Y5__c = (oppDelWrap.sumOfFteYr5==0)?0: (oppDelWrap.sumOfRunYr5/ oppDelWrap.sumOfFteYr5).setScale(4);
            delLoc.Cost_Per_FTE_Y6__c = (oppDelWrap.sumOfFteYr6==0)?0: (oppDelWrap.sumOfRunYr6/ oppDelWrap.sumOfFteYr6).setScale(4);
            delLoc.Cost_Per_FTE_Y7__c = (oppDelWrap.sumOfFteYr7==0)?0: (oppDelWrap.sumOfRunYr7/ oppDelWrap.sumOfFteYr7).setScale(4);
            delLoc.Cost_Per_FTE_Y8__c = (oppDelWrap.sumOfFteYr8==0)?0: (oppDelWrap.sumOfRunYr8/ oppDelWrap.sumOfFteYr8).setScale(4);
            delLoc.Cost_Per_FTE_Y9__c = (oppDelWrap.sumOfFteYr9==0)?0: (oppDelWrap.sumOfRunYr9/ oppDelWrap.sumOfFteYr9).setScale(4);
            delLoc.Cost_Per_FTE_Y10__c = (oppDelWrap.sumOfFteYr10==0)?0: (oppDelWrap.sumOfRunYr10/ oppDelWrap.sumOfFteYr10).setScale(4);
            
            
        }   
    }
    
    System.debug('delLocList >>>>' + delLocList);
    }
}


            
            /*
            svcPyrWrap   = new PyramidRichnessWrapper();
           
            
            if(!svcPyrMap.containsKey(delLoc.Offering_Service__c)){
                svcPyrWrap   = new PyramidRichnessWrapper();
                svcPyrWrap.serviceId = delLoc.Offering_Service__c;
            }
            else{
                svcPyrWrap = svcPyrMap.get(delLoc.Offering_Service__c);
            }
            
            
            //dLocWrap= new PyramidRichnessWrapper();
              svcPyrWrap.sumOfSumFTEYr1+= oppDelWrap.sumOfSumFTEYr1;
              svcPyrWrap.sumOfSumFTEYr2+= oppDelWrap.sumOfSumFTEYr2;
              svcPyrWrap.sumOfSumFTEYr3+= oppDelWrap.sumOfSumFTEYr3;
              svcPyrWrap.sumOfSumFTEYr4+= oppDelWrap.sumOfSumFTEYr4;
              svcPyrWrap.sumOfSumFTEYr5+= oppDelWrap.sumOfSumFTEYr5;
              svcPyrWrap.sumOfSumFTEYr6+= oppDelWrap.sumOfSumFTEYr6;
              svcPyrWrap.sumOfSumFTEYr7+= oppDelWrap.sumOfSumFTEYr7;
              svcPyrWrap.sumOfSumFTEYr8+= oppDelWrap.sumOfSumFTEYr8;
              svcPyrWrap.sumOfSumFTEYr9+= oppDelWrap.sumOfSumFTEYr9;
              svcPyrWrap.sumOfSumFTEYr10+= oppDelWrap.sumOfSumFTEYr10;
              svcPyrWrap.effSumOfSumFTEYr1+= oppDelWrap.effsumOfSumFTEYr1;
              svcPyrWrap.effsumOfSumFTEYr2+= oppDelWrap.effsumOfSumFTEYr2;
              svcPyrWrap.effsumOfSumFTEYr3+= oppDelWrap.effsumOfSumFTEYr3;
              svcPyrWrap.effsumOfSumFTEYr4+= oppDelWrap.effsumOfSumFTEYr4;
              svcPyrWrap.effsumOfSumFTEYr5+= oppDelWrap.effsumOfSumFTEYr5;
              svcPyrWrap.effsumOfSumFTEYr6+= oppDelWrap.effsumOfSumFTEYr6;
              svcPyrWrap.effsumOfSumFTEYr7+= oppDelWrap.effsumOfSumFTEYr7;
              svcPyrWrap.effsumOfSumFTEYr8+= oppDelWrap.effsumOfSumFTEYr8;
              svcPyrWrap.effsumOfSumFTEYr9+= oppDelWrap.effsumOfSumFTEYr9;
              svcPyrWrap.effsumOfSumFTEYr10+= oppDelWrap.effsumOfSumFTEYr10;
              
                svcPyrWrap.sumOfRunYr1+= oppDelWrap.sumOfRunYr1;
                svcPyrWrap.sumOfRunYr2+= oppDelWrap.sumOfRunYr2;
                svcPyrWrap.sumOfRunYr3+= oppDelWrap.sumOfRunYr3;
                svcPyrWrap.sumOfRunYr4+= oppDelWrap.sumOfRunYr4;
                svcPyrWrap.sumOfRunYr5+= oppDelWrap.sumOfRunYr5;
                svcPyrWrap.sumOfRunYr6+= oppDelWrap.sumOfRunYr6;
                svcPyrWrap.sumOfRunYr7+= oppDelWrap.sumOfRunYr7;
                svcPyrWrap.sumOfRunYr8+= oppDelWrap.sumOfRunYr8;
                svcPyrWrap.sumOfRunYr9+= oppDelWrap.sumOfRunYr9;
                svcPyrWrap.sumOfRunYr10+= oppDelWrap.sumOfRunYr10;
                svcPyrWrap.sumOfFteYr1+= oppDelWrap.sumOfFteYr1;
                svcPyrWrap.sumOfFteYr2+= oppDelWrap.sumOfFteYr2;
                svcPyrWrap.sumOfFteYr3+= oppDelWrap.sumOfFteYr3;
                svcPyrWrap.sumOfFteYr4+= oppDelWrap.sumOfFteYr4;
                svcPyrWrap.sumOfFteYr5+= oppDelWrap.sumOfFteYr5;
                svcPyrWrap.sumOfFteYr6+= oppDelWrap.sumOfFteYr6;
                svcPyrWrap.sumOfFteYr7+= oppDelWrap.sumOfFteYr7;
                svcPyrWrap.sumOfFteYr8+= oppDelWrap.sumOfFteYr8;
                svcPyrWrap.sumOfFteYr9+= oppDelWrap.sumOfFteYr9;
                svcPyrWrap.sumOfFteYr10+= oppDelWrap.sumOfFteYr10;


              
              svcPyrMap.put(delLoc.Offering_Service__c, svcPyrWrap);
              

                        
            
            System.debug('svcPyrWrap >> ' + svcPyrWrap);
            svcPyrWrap   = new PyramidRichnessWrapper();
             oppDelWrap= new PyramidRichnessWrapper();
             */