/*
  @Author: 
  @Name: UTIL_ConstantsTest
  @Created Date: 01 January 2015
  @Description: This is a test class UTIL_ConstantsTest.
  @version: 1.0
*/
@isTest
public class UTIL_ConstantsTest{
/*
  @Author: 
  @Name: UtilTestMethod
  @Created Date: 01 January 2015
  @Description: This is a test method UtilTestMethod for UTIL_Constants.
  @version: 1.0
*/
 static testMethod  void UtilTestMethod()
    { 
        UTIL_Constants cover_it_be = new UTIL_Constants();
    }
}